# https://www.appveyor.com/docs/appveyor-yml/
version: 1.0.{build}

image: Visual Studio 2019

build:
  verbosity: minimal

# scripts that run after cloning repository
install:
  - ps: |
      Get-ComputerInfo  | select windowsversion
  - ps: |
      [environment]::OSVersion
  - ps: |
      & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productDisplayVersion

  # Remove system's llvm
  - ps: |
      $previous_clang_installation = (get-command clang).Source | Split-Path -Parent | Split-Path -Parent
      write-host "The following folder will be deleted: $previous_clang_installation" -ForegroundColor Black -BackgroundColor DarkYellow
      ls $previous_clang_installation
      rm -Recurse -Force $previous_clang_installation

      ls $($previous_clang_installation | Split-Path -Parent)

  - ps: scripts/get-binaries.ps1

build_script:
  - ps: scripts/build-project.ps1

test_script:
  - ps: |
      Set-PSDebug -Trace 1
      pushd .\src

      get-command api-ms-win-core-synch-l1-2-0.dll | Format-List *
      get-command python39.dll | Format-List *
      get-command KERNEL32.dll | Format-List *
      .\py_file_run.exe C:\Python39-x64 .\test.py


# on_failure:
#   # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
