# https://www.appveyor.com/docs/appveyor-yml/
version: 1.0.{build}

image: Visual Studio 2019

build:
  verbosity: minimal

# scripts that run after cloning repository
install:
  - ps: |
      & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productDisplayVersion

  - ps: |
      curl https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/LLVM-13.0.0-win64.exe -o llvm.exe
      7z x llvm.exe -ollvm

  - ps: |
      write-host "LLVM paths" -ForegroundColor Black -BackgroundColor DarkYellow
      write-host "$(get-location)\llvm\bin"
      write-host "$(get-location)\llvm\lib\clang\13.0.0\lib\windows"

  - ps: |
      Invoke-WebRequest https://github.com/sharkdp/fd/releases/download/v8.2.1/fd-v8.2.1-i686-pc-windows-msvc.zip -OutFile fd.zip
      7z x fd.zip -o"C:\Windows"

  - ps: |
      write-host "Finding files" -ForegroundColor Black -BackgroundColor DarkYellow
      fd.exe -HI clang_rt.asan_dynamic-x86_64.dll
      fd.exe -HI clang_rt.asan_dll_thunk-x86_64.lib
      fd.exe -HI clang_rt.asan-x86_64.lib
      fd.exe -HI clang_rt.asan_cxx-x86_64.lib
      fd.exe -HI clang.exe
      fd.exe -HI lld-link.exe

  - ps: |
      $env:PATH="C:\Python39-x64\Scripts;$env:PATH"

      py -3.9-64 -m pip install -U pip wheel
      py -3.9-64 -m pip install cffi

build_script:
  - ps: |
      $env:PATH="$(Get-Location)\llvm\bin;$env:PATH"
      $env:PATH="$(Get-Location)\llvm\lib\clang\13.0.0\lib\windows;$env:PATH"

      write-host "Command locations" -ForegroundColor Black -BackgroundColor DarkYellow
      get-command clang
      get-command lld-link

      # stderr to stdout to avoid appveyor crashing on warnings
      py -3.9-64 src

test_script:
  - ps: ./src/py_file_run.exe C:\Python39-x64 .\test.py


on_failure:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
