# https://www.appveyor.com/docs/appveyor-yml/
version: 1.0.{build}

image: Visual Studio 2019

build:
  verbosity: minimal

# scripts that run after cloning repository
install:
  - ps: |
      [environment]::OSVersion
      & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property catalog_productDisplayVersion

  - ps: scripts/get-binaries.ps1

build_script:
  - ps: scripts/build-project.ps1

test_script:
  - ps: ./src/py_file_run.exe C:\Python39-x64 .\test.py


on_failure:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
